"""Schemas for resume parsing and RAG matchmaking."""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class CandidateProfile(BaseModel):
    """Structured profile extracted from resume by Groq LLM."""
    name: Optional[str] = Field(default="Candidate", description="Full name of the candidate")
    role_preferences: List[str] = Field(default_factory=list, description="Preferred job roles or titles")
    years_of_experience: Optional[float] = Field(default=0.0, description="Estimated total years of relevant experience")
    provided_experience: Optional[str] = Field(default=None, description="User-specified current experience (e.g. Fresher / 2+ Years)")
    technical_skills: List[str] = Field(default_factory=list, description="Core programming languages, frameworks, databases, tools")
    soft_skills: List[str] = Field(default_factory=list, description="Interpersonal and collaboration strengths")
    domain_experience: List[str] = Field(default_factory=list, description="Industry domains like FinTech, Cloud, AI, E-commerce")
    summary: str = Field(default="", description="Executive professional summary")


class CompanyFitItem(BaseModel):
    """Personalized fit evaluation for a matched company."""
    company: str
    role: str
    experience_level: Optional[str] = None
    source: str = Field(description="'live' or 'excel'")
    similarity_score: float = Field(description="Normalized similarity score (0.0 to 1.0)")
    distance: float = Field(description="ChromaDB vector distance")
    why_perfect_fit: str = Field(description="Personalized rationale generated by Groq on why candidate is a fit")
    key_matching_points: List[str] = Field(default_factory=list, description="Matching skills, tech stacks, or domains")
    recommendations: Optional[str] = Field(default=None, description="Actionable advice for interview or profile enhancement")
    job_url: Optional[str] = None


class ResumeMatchResponse(BaseModel):
    """Response schema for POST /api/match/resume."""
    success: bool
    message: str
    cloudinary_url: str
    candidate_profile: CandidateProfile
    source_used: str = Field(description="Which ChromaDB data tier was matched ('live' vs 'excel')")
    is_fallback: bool = Field(description="True if live data had poor score / empty and excel was used")
    provided_experience: Optional[str] = Field(default=None, description="User-specified current experience factored into RAG")
    top_company_fits: List[CompanyFitItem]
    record_id: Optional[str] = None
